let circulo = new Circle();
let circulo2 = new Circle();
let rectangulo = new Rectangle();
let rectangulo2 = new Rectangle();
let triangle = new Triangle();
circulo2.setValues(500,500,40,'#89AC76');
rectangulo2.setValues(100,100,40,40,'#89AC76');
circulo.dibujar();
circulo2.dibujar();
rectangulo.dibujar();
rectangulo2.dibujar();
triangle.dibujar();
